import type { Dictionary } from './dictionary';

export const EN: Dictionary = {
  nav: {
    home: 'Home',
    about: 'About',
    experience: 'Experience',
    projects: 'Projects',
    skills: 'Skills',
    contact: 'Contact',
    lab: 'AI Lab',
  },
  hero: {
    greeting: 'Hi, I am',
    passion: 'Full Stack Developer passionate about',
    subtitle:
      'Building innovative web solutions with modern technologies and a passion for clean, efficient code.',
    viewProjects: 'View Projects',
    downloadCv: 'Download CV',
    contact: 'Contact',
  },
  about: {
    title: 'About me',
    role: 'Full Stack Developer',
    funFactsTitle: 'Fun Facts About Me',
    facts: [
      'Loves football',
      'Always learning AI',
      'Coffee enthusiast',
      'Coding with music',
      'Clean code advocate',
      'Problem solver',
    ],
    yearsLearning: 'Years Learning',
    projectsBuilt: 'Projects Built',
    technologies: 'Technologies',
  },
  experience: {
    title: 'Experience',
    responsibilities: 'Responsibilities',
    technologies: 'Technologies used',
    current: 'Currently employed and loving it!',
  },
  projects: {
    title: 'Projects',
    subtitle:
      'A selection of projects I have worked on, showcasing my skills in full stack development, artificial intelligence and modern technologies.',
    stackTitle: 'Tech Stack',
    viewGithub: 'View on GitHub',
    liveDemo: 'Live Demo',
    viewMore: 'See more projects on GitHub',
  },
  skills: {
    title: 'Skills',
    subtitle:
      'My technical skills organised by category, from frontend and backend development to emerging technologies and specialised tools.',
    overviewTitle: 'Skills Overview',
    technologies: 'Technologies',
    expertLevel: 'Expert Level',
    learningAi: 'Learning AI/ML',
    alwaysLearning: 'Always Learning',
    downloadTitle: 'Download My CV',
    downloadText:
      'Get a detailed overview of my experience, education, and technical skills in PDF format.',
    download: 'Download CV',
    levels: {
      expert: 'Expert',
      advanced: 'Advanced',
      intermediate: 'Intermediate',
      learning: 'Learning',
      beginner: 'Beginner',
    },
  },
  contact: {
    title: 'Contact',
    subtitle:
      'Do you have a project in mind or want to collaborate? I would love to hear about your idea and explore how we can work together.',
    formTitle: 'Send me a message',
    name: 'Full name',
    namePlaceholder: 'Your name',
    email: 'Email',
    emailPlaceholder: 'you@email.com',
    message: 'Message',
    messagePlaceholder: 'Tell me about your project or idea...',
    send: 'Send message',
    sending: 'Sending...',
    infoTitle: 'Contact information',
    locationLabel: 'Location',
    locationValue: 'Seville, Spain',
    socialTitle: 'Social links',
    availableTitle: 'Available for projects',
    availableText: 'Currently open to new opportunities and collaborations',
    sent: 'Message sent successfully! I will get back to you soon.',
  },
  footer: {
    tagline:
      'Full Stack Developer passionate about building innovative solutions with modern technologies.',
    quickLinks: 'Quick links',
    follow: 'Follow me',
    rights: 'All rights reserved.',
    madeWith: 'Made with',
    alwaysEvolving: 'Always evolving',
    builtWith: 'Built with React, TypeScript, Tailwind CSS and Motion',
  },
  aiLab: {
    title: 'AI Lab',
    subtitle:
      'The assistant engineering on display: hybrid architecture, live status and evaluation results.',
    statusTitle: 'Assistant status',
    online: 'Online',
    degraded: 'Degraded',
    offline: 'Offline',
    metricsTitle: 'Latest evaluation (retrieval and refusal)',
    recall: 'recall@5',
    refusal: 'out-of-domain refusal',
    leaks: 'leaks',
    model: 'embedding model',
    privacyTitle: 'What the assistant can see',
    privacyText:
      'It only indexes notes in the Public folder with cv_public: true, with sensitive-data redaction. The private vault is never exposed.',
    linksTitle: 'Links',
    repo: 'GitHub repository',
    evaluation: 'Methodology and dataset',
    diagramAlt:
      'Architecture diagram: Caddy, FastAPI, Chroma on the HP node and Ollama on the GPU tower and Dell node over Tailscale',
  },
  chat: {
    title: 'Rafael assistant',
    disclaimer: 'AI assistant; it only answers with public portfolio information',
    starters: [
      'Which AI projects has Rafael built?',
      'What is his backend stack?',
      'What experience does he have with Docker and Linux?',
      'What is he working on right now?',
    ],
    inputPlaceholder: 'Type your question…',
    send: 'Send message',
    stop: 'Stop the response',
    copy: 'Copy response',
    useful: 'Helpful answer',
    notUseful: 'Unhelpful answer',
    newConversation: 'New conversation',
    close: 'Close assistant',
    open: 'Open assistant',
    retry: 'Retry',
    limit: 'You have reached the message limit.',
    limitRetry: 'Try again in {seconds} s',
    offline: 'The assistant is under maintenance.',
    degraded: 'Responses may be a bit slower than usual.',
    refused: 'Would you rather talk to Rafael?',
    contact: 'Use the contact form',
    sources: 'Sources',
    empty: 'Ask me about his experience, projects or tech stack.',
  },
};
