import type { Dictionary } from './dictionary';

export const ES: Dictionary = {
  nav: {
    home: 'Inicio',
    about: 'Sobre mí',
    experience: 'Experiencia',
    projects: 'Proyectos',
    skills: 'Habilidades',
    contact: 'Contacto',
    lab: 'AI Lab',
  },
  hero: {
    greeting: 'Hi, I am',
    passion: 'Full Stack Developer passionate about',
    subtitle:
      'Building innovative web solutions with modern technologies and a passion for clean, efficient code.',
    viewProjects: 'View Projects',
    downloadCv: 'Download CV',
    contact: 'Contact',
  },
  about: {
    title: 'Sobre mí',
    role: 'Full Stack Developer',
    funFactsTitle: 'Fun Facts About Me',
    facts: [
      'Loves football',
      'Always learning AI',
      'Coffee enthusiast',
      'Coding with music',
      'Clean code advocate',
      'Problem solver',
    ],
    yearsLearning: 'Years Learning',
    projectsBuilt: 'Projects Built',
    technologies: 'Technologies',
  },
  experience: {
    title: 'Experiencia',
    responsibilities: 'Responsabilidades',
    technologies: 'Tecnologías utilizadas',
    current: 'Currently employed and loving it!',
  },
  projects: {
    title: 'Proyectos',
    subtitle:
      'Una selección de proyectos en los que he trabajado, demostrando mis habilidades en desarrollo full stack, inteligencia artificial y tecnologías modernas.',
    stackTitle: 'Stack Tecnológico',
    viewGithub: 'View on GitHub',
    liveDemo: 'Live Demo',
    viewMore: 'Ver más proyectos en GitHub',
  },
  skills: {
    title: 'Habilidades',
    subtitle:
      'Mis competencias técnicas organizadas por categoría, desde desarrollo frontend y backend hasta tecnologías emergentes y herramientas especializadas.',
    overviewTitle: 'Skills Overview',
    technologies: 'Technologies',
    expertLevel: 'Expert Level',
    learningAi: 'Learning AI/ML',
    alwaysLearning: 'Always Learning',
    downloadTitle: 'Download My CV',
    downloadText:
      'Get a detailed overview of my experience, education, and technical skills in PDF format.',
    download: 'Download CV',
    levels: {
      expert: 'Expert',
      advanced: 'Advanced',
      intermediate: 'Intermediate',
      learning: 'Learning',
      beginner: 'Beginner',
    },
  },
  contact: {
    title: 'Contacto',
    subtitle:
      '¿Tienes un proyecto en mente o quieres colaborar? Me encantaría escuchar sobre tu idea y explorar cómo podemos trabajar juntos.',
    formTitle: 'Envíame un mensaje',
    name: 'Nombre completo',
    namePlaceholder: 'Tu nombre',
    email: 'Email',
    emailPlaceholder: 'tu@email.com',
    message: 'Mensaje',
    messagePlaceholder: 'Cuéntame sobre tu proyecto o idea...',
    send: 'Enviar mensaje',
    sending: 'Enviando...',
    infoTitle: 'Información de contacto',
    locationLabel: 'Ubicación',
    locationValue: 'Sevilla, España',
    socialTitle: 'Redes sociales',
    availableTitle: 'Disponible para proyectos',
    availableText: 'Actualmente abierto a nuevas oportunidades y colaboraciones',
    sent: '¡Mensaje enviado correctamente! Te responderé pronto.',
  },
  footer: {
    tagline:
      'Full Stack Developer apasionado por crear soluciones innovadoras con tecnologías modernas.',
    quickLinks: 'Enlaces rápidos',
    follow: 'Sígueme',
    rights: 'Todos los derechos reservados.',
    madeWith: 'Hecho con',
    alwaysEvolving: 'Siempre en evolución',
    builtWith: 'Construido con React, TypeScript, Tailwind CSS y Motion',
  },
  aiLab: {
    title: 'AI Lab',
    subtitle:
      'La ingeniería del asistente, a la vista: arquitectura híbrida, estado en vivo y resultados de evaluación.',
    statusTitle: 'Estado del asistente',
    online: 'En línea',
    degraded: 'Degradado',
    offline: 'Sin conexión',
    metricsTitle: 'Última evaluación (recuperación y rechazo)',
    recall: 'recall@5',
    refusal: 'rechazo fuera de dominio',
    leaks: 'fugas',
    model: 'modelo de embeddings',
    privacyTitle: 'Qué puede ver el asistente',
    privacyText:
      'Solo indexa notas de la carpeta Public con cv_public: true, con redacción de datos sensibles. El vault privado nunca se expone.',
    linksTitle: 'Enlaces',
    repo: 'Repositorio en GitHub',
    evaluation: 'Metodología y dataset',
    diagramAlt:
      'Diagrama de arquitectura: Caddy, FastAPI, Chroma en el nodo HP y Ollama en la torre GPU y el nodo Dell por Tailscale',
  },
  chat: {
    title: 'Asistente de Rafael',
    disclaimer: 'Asistente de IA; solo responde con información pública del portfolio',
    starters: [
      '¿Qué proyectos de IA ha desarrollado Rafael?',
      '¿Cuál es su stack de backend?',
      '¿Qué experiencia tiene con Docker y Linux?',
      '¿Qué está haciendo ahora mismo?',
    ],
    inputPlaceholder: 'Escribe tu pregunta…',
    send: 'Enviar mensaje',
    stop: 'Detener la respuesta',
    copy: 'Copiar respuesta',
    useful: 'Respuesta útil',
    notUseful: 'Respuesta no útil',
    newConversation: 'Nueva conversación',
    close: 'Cerrar el asistente',
    open: 'Abrir el asistente',
    retry: 'Reintentar',
    limit: 'Has alcanzado el límite de mensajes.',
    limitRetry: 'Reintenta en {seconds} s',
    offline: 'El asistente está en mantenimiento.',
    degraded: 'Respuestas algo más lentas de lo normal.',
    refused: '¿Prefieres hablar con Rafael?',
    contact: 'Usa el formulario de contacto',
    sources: 'Fuentes consultadas',
    empty: 'Pregúntame por su experiencia, proyectos o stack técnico.',
  },
};
